version: '3'

services:
  database:
    image: postgres:11-alpine
    ports:
      - "5433:5433"
    volumes:
      - ./postgres:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main